### PR TITLE
dynamic version set

### PR DESCRIPTION
**Pull request by jyore**
Code pulls the supported version list and grabs the max version out of the list. The minimum of that list and the max version that our API supports is selected and the settings are updated.

### CODE REVIEW

**Comment by sabre1041** [comment]
Tested out fix against ose branch to validate version changes. Modifications made partially resolved issue. Version is being set correctly upon the successful callback after login. However, there are instances where an error can occur prior to the update of version.

Tested Scenario:
1. Modified max supported api = 1.7 (Matched OpenShift Online)
2. Logged in. API Version set at 1.7. 
3. Logged out
4. Attempted to login to OSE Test instance (API version 1.6)
5. Error occurred. This was due to the fact a version property was being set as part of the request. Since it had an API version higher than what was supported, the call failed. The solution that I found that worked was to add `app.set_api_version(null);` in the logout method to force future requests to forgo passing a version number until it is able to update itself with the appropriate value from the accessed OpenShift environment

**Comment by jyore** [comment]
He max supported version in the max version our framework supports. Since
we have not verified 1.7 (issue in backlog to acclimate this change), the
max version should stay at 1.6. In the version select code, the min
function call on our max version and the max version coming back from
openshift ensures that we are not overstepping our own support nor the
openshift platform support.

Forgot that the first call would pickup the previous version, so mulling it
out on logout is a good safe guard.

**Comment by sabre1041** [comment]
I only temporarily changed the max version locally to be able to replicate an environment where two different API versions are present (since the internal OSE instance supports version 1.6 and the app's max version is set at 1.6). 

The reason the null on logout is required is because when issuing the first request to a new OpenShift environment after previously being logged in to another environment with a higher supported API version, the request sends the API version along with the request which fails (406). This will always occur if you login to one environment, logout, and then login to another environment that has a higher supported API that both the app and the environment supports.

**Comment by jyore** [comment]
Ok. Yeah I am fine with the null on logout...may not have been clear in
last email?

**Pull request merged**
