### PR TITLE
added icons, splash screen and new hook

### PR DESCRIPTION
**Pull request by ghost**
Added after_prepare hook to copy over IOS icons and splash screens as
well as Andriod icons.  Also updated config.xml to use new icons and
splash screens for phone gap build.

### CODE REVIEW

**Comment by jyore** [comment]
pulled down and tried to build. getting error:

[phonegap] adding the Android platform...
   [error] Script "/home/jyore/Code/phonegap/forks/openshift-mobile/.cordova/hooks/after_prepare/osm_resource_files.js" exited with non-zero status code. Aborting. Output: 
/home/jyore/Code/phonegap/forks/openshift-mobile/.cordova/hooks/after_prepare/osm_resource_files.js:10
{"www/res/icon/ios/icon-40@2x.png": "platforms/ios/OpenShift Mobile/Resources/
^
SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:69:16)
    at Module._compile (module.js:432:25)
    at Object.Module._extensions..js (module.js:467:10)
    at Module.load (module.js:349:32)
    at Function.Module._load (module.js:305:12)
    at Function.Module.runMain (module.js:490:10)
    at startup (node.js:121:16)
    at node.js:757:3

**Comment by ghost** [comment]
I think it's choking on the space. I'll probably have to escape it. 

You building on windows or Linux?
- zach

**Comment by jyore** [comment]
Linux

**Comment by sabre1041** [comment]
There is an extra bracket at the beginning of the filestocopy array. Also, the source path on the android resources has the name android misspelled. Finally an additional folder called drawable (96x96) must have an icon added 

```
{"www/res/icon/android/icon-96-xhdpi.png": "platforms/android/res/drawable/icon.png"}, 
```

**Comment by jyore** [comment]
saw this too

remove the '{' from line 7 in .cordova/hooks/after_prepare/osm_resource_files.js and it fixes the compilation problem

All the icons are not showing correctly, however.

**Comment by jyore** [comment]
As @sabre1041  mentioned, there are misspellings as well:

line 33-37 `andriod` instead of `android`
    //andriod icon
    {"www/res/icon/andriod/icon-36-ldpi.png": "platforms/android/res/drawable-ldpi/icon.png"},
    {"www/res/icon/andriod/icon-48-mdpi.png": "platforms/android/res/drawable-mdpi/icon.png"},
    {"www/res/icon/andriod/icon-72-hdpi.png": "platforms/android/res/drawable-hdpi/icon.png"},
    {"www/res/icon/andriod/icon-96-xhdpi.png": "platforms/android/res/drawable-xhdpi/icon.png"},
    {"www/res/icon/andriod/icon-144-xxhdpi.png": "platforms/android/res/drawable-xxhdpi/icon.png"},

**Comment by ghost** [comment]
Thanks for looking at this, guys. I'll amend the pull request with the fixes.

**Pull request merged**
